# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-moonforge-rauc-update"
BBFILE_PATTERN_meta-moonforge-rauc-update = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-moonforge-rauc-update = "6"

LAYERDEPENDS_meta-moonforge-rauc-update = " \
    core \
    meta-moonforge-rauc \
"
LAYERSERIES_COMPAT_meta-moonforge-rauc-update = "scarthgap"
