# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 Igalia S.L.

BB_CONF_FRAGMENT_SUMMARY = "Podman container engine image packages"
BB_CONF_FRAGMENT_DESCRIPTION = "Installs Podman, podman-compose and ca-certificates into the image."

CORE_IMAGE_EXTRA_INSTALL += " \
    podman \
    podman-compose \
    ca-certificates \
"
