[system]
compatible=qemux86-64
bootloader=grub
grubenv=/boot/grubenv
data-directory=/data/

[keyring]
path=ca.cert.pem

[slot.rootfs.0]
device=/dev/sda2
type=ext4
bootname=A

[slot.rootfs.1]
device=/dev/sda3
type=ext4
bootname=B
