# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 Igalia S.L.

BB_CONF_FRAGMENT_SUMMARY = "RAUC update helper image packages"
BB_CONF_FRAGMENT_DESCRIPTION = "Installs the rauc-update helper into the image."

CORE_IMAGE_EXTRA_INSTALL += " \
    rauc-update \
"
