# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILES_DYNAMIC += " \
    meta-moonforge-qemu:${LAYERDIR}/dynamic-layers/meta-moonforge-qemu/*/*/*.bb \
    meta-moonforge-qemu:${LAYERDIR}/dynamic-layers/meta-moonforge-qemu/*/*/*.bbappend \
    meta-moonforge-raspberrypi:${LAYERDIR}/dynamic-layers/meta-moonforge-raspberrypi/*/*/*.bb \
    meta-moonforge-raspberrypi:${LAYERDIR}/dynamic-layers/meta-moonforge-raspberrypi/*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "meta-moonforge-rauc"
BBFILE_PATTERN_meta-moonforge-rauc = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-moonforge-rauc = "7"

LAYERDEPENDS_meta-moonforge-rauc = " \
    core \
    rauc \
"
LAYERRECOMMENDS_meta-moonforge-rauc = " \
    meta-moonforge-qemu \
    meta-moonforge-raspberrypi \
"
LAYERSERIES_COMPAT_meta-moonforge-rauc = "scarthgap"

RAUC_KEY_FILE ?= "${LAYERDIR}/files/meta-moonforge-demo-1.key.pem"
RAUC_CERT_FILE ?= "${LAYERDIR}/files/meta-moonforge-demo-1.cert.pem"
RAUC_KEYRING_FILE ?= "${LAYERDIR}/recipes-core/rauc/files/ca.cert.pem"
