#
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2025 Igalia S.L.
#

DISTRO = "moonforge"
DISTRO_NAME = "Moonforge (Moonforge Linux Distribution)"
DISTRO_VERSION = "1.0"
DISTRO_CODENAME = "main"
SDK_VENDOR = "-moonforgesdk"
SDK_VERSION = "${@d.getVar('DISTRO_VERSION').replace('snapshot-${METADATA_REVISION}', 'snapshot')}"
SDK_VERSION[vardepvalue] = "${SDK_VERSION}"

MAINTAINER = "The Moonforge team <contact@moonforgelinux.com>"

TARGET_VENDOR = "-moonforge"

LOCALCONF_VERSION = "2"

# Distro features should be specified in layer kas fragments
DISTRO_FEATURES_BACKFILL_CONSIDERED = "pulseaudio sysvinit gobject-introspection-data"

# Override these in moonforge based distros
MOONFORGE_DEFAULT_DISTRO_FEATURES = "ptest multiarch"
MOONFORGE_DEFAULT_EXTRA_RDEPENDS = "packagegroup-core-boot"
MOONFORGE_DEFAULT_EXTRA_RRECOMMENDS = "kernel-module-af-packet"

DISTRO_FEATURES ?= "${DISTRO_FEATURES_DEFAULT} ${MOONFORGE_DEFAULT_DISTRO_FEATURES}"

PREFERRED_VERSION_linux-yocto ?= "6.6%"
PREFERRED_VERSION_linux-yocto-rt ?= "6.6%"

SDK_NAME = "${DISTRO}-${TCLIBC}-${SDKMACHINE}-${IMAGE_BASENAME}-${TUNE_PKGARCH}-${MACHINE}"
SDKPATHINSTALL = "/opt/${DISTRO}/${SDK_VERSION}"

DISTRO_EXTRA_RDEPENDS += "${MOONFORGE_DEFAULT_EXTRA_RDEPENDS}"
DISTRO_EXTRA_RRECOMMENDS += "${MOONFORGE_DEFAULT_EXTRA_RRECOMMENDS}"

TCLIBCAPPEND = ""

PACKAGE_CLASSES ?= "package_rpm"

SANITY_TESTED_DISTROS ?= " \
            debian-13 \n \
            "

require conf/distro/include/no-static-libs.inc
require conf/distro/include/yocto-uninative.inc
require conf/distro/include/security_flags.inc
INHERIT += "uninative"

BB_SIGNATURE_HANDLER ?= "OEEquivHash"
BB_HASHSERVE ??= "auto"

MOONFORGE_INIT_MANAGER = "systemd"
INIT_MANAGER ?= "${MOONFORGE_INIT_MANAGER}"
