# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 Igalia S.L.

BB_CONF_FRAGMENT_SUMMARY = "Docker container engine image packages"
BB_CONF_FRAGMENT_DESCRIPTION = "Installs the Docker (moby) engine, docker-compose and the Docker configuration into the image."

CORE_IMAGE_EXTRA_INSTALL += " \
    docker-moby \
    docker-compose \
    docker-config \
"
